#!/bin/sh
# Manage external display
#
# 
function external_display() {
  case $1 in
    on)
      echo "turning display on above" >&2
      xrandr --output LVDS1 --auto --output HDMI1 --auto --above LVDS1
      ;;
    underscan)
      echo "turning display on above with underscan" >&2
      xrandr --output LVDS1 --auto --output HDMI1 --auto --above LVDS1 --set underscan on --set "underscan hborder" $2 --set "underscan vborder" $3
      ;;
    off)
      echo "turning display off" >&2
      xrandr --output LVDS1 --auto --output HDMI1 --off
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
}
