#!/usr/bin/env bash
#
# Run all arch configure scripts.

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name configure_for_arch.sh | while read installer ; do sh -c "${installer}" ; done
