#!/bin/sh
#
# mail/notmuch
#
# symlinks hook scripts to the correct location

# move to directory of script
cd "$(dirname "$0")"

echo -e "\t - setup hooks."
mkdir -p ~/.mail/.notmuch/hooks
ln -sr post-new ~/.mail/.notmuch/hooks/post-new

exit 0
