#!/bin/sh

notmuch tag +sent -- 'folder:"hmc/[Gmail]/Sent Mail"'
afew -vv --tag --new 
afew -vv --move-mail --all 
notmuch tag -unread -- tag:draft or tag:sent
notmuch tag -unread -inbox -- tag:inbox and not folder:/.*inbox/
